export const GameConfig = {
    // Player
    PLAYER_WALK_SPEED: 3.0,
    PLAYER_SPRINT_SPEED: 6.0,
    PLAYER_CROUCH_SPEED: 1.5,
    PLAYER_HEIGHT: 1.7,
    PLAYER_CROUCH_HEIGHT: 0.8,
    PLAYER_RADIUS: 0.4,
    MAX_STAMINA: 100,
    STAMINA_DRAIN: 20,
    STAMINA_REGEN: 10,
    
    // Ghost (Mara) Base Stats
    GHOST_WANDER_SPEED: 1.8,
    GHOST_INVESTIGATE_SPEED: 2.5,
    GHOST_CHASE_SPEED: 4.5,
    GHOST_HEARING_RADIUS: 12.0,
    GHOST_CATCH_DISTANCE: 1.2,
    
    // Noise Levels
    NOISE_STATIONARY: 0.0,
    NOISE_CROUCH: 0.05,
    NOISE_WALK: 0.3,
    NOISE_SPRINT: 0.9,
    
    // Interaction
    INTERACT_DISTANCE: 2.5,
    
    // Items
    ITEM_KEY_FRONT_DOOR: 'KEY_FRONT_DOOR',
    ITEM_KEY_CAR: 'KEY_CAR',
    ITEM_KEY_BASEMENT: 'KEY_BASEMENT_HATCH',
    ITEM_BATTERY: 'BATTERY',
    ITEM_FLASHLIGHT: 'FLASHLIGHT',
    ITEM_HAMMER: 'HAMMER',
    
    // Game States
    STATE_LOADING: 'LOADING',
    STATE_AUDIO_UNLOCK: 'AUDIO_UNLOCK',
    STATE_MAIN_MENU: 'MAIN_MENU',
    STATE_STORY: 'STORY',
    STATE_PLAYING: 'PLAYING',
    STATE_PAUSED: 'PAUSED',
    STATE_VICTORY: 'VICTORY',
    STATE_GAME_OVER: 'GAME_OVER',
    
    // Difficulty
    DIFF_PRACTICE: 'PRACTICE',
    DIFF_NORMAL: 'NORMAL',
    DIFF_EXTREME: 'EXTREME',
    
    // Session Seed
    SESSION_SEED: Date.now() % 99991
};
